import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useEffect, useState } from "react";

const fetchCompanies = () => {
  return fetch("http://localhost:20002/companiesWithDeals")
    .then((res) => res.json())
    .then((res) => {
      console.log(res);
      return res;
    })
    .catch((err) => {
      console.error(err);
    });
};

const Home: NextPage = () => {
  const [companies, setCompanies] = useState(null);
  useEffect(() => {
    fetchCompanies().then((result) => {
      if (result) setCompanies(result);
    });
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div>
          {companies ? (
            <div>
              {Object.keys(companies).map((index) => (
                <p key={index}>
                  <span>{JSON.stringify(companies[index]["Company"])}</span>
                  <br />
                  <span>{JSON.stringify(companies[index]["Deals"])}</span>
                  <br />
                  <br />
                </p>
              ))}
            </div>
          ) : (
            <div></div>
          )}
        </div>
      </main>
    </div>
  );
};

export default Home;
